=== bugati23/Multithreading/src/test/resources/Train.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/trains"
        xmlns:tns="http://www.example.com/trains"
        elementFormDefault="qualified">
    <element name="trains">
        <complexType>
            <sequence>
                <element name="train"
                         type="tns:Train"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Train">
        <all>
            <element name="number" type="positiveInteger"/>
            <element name="direction" type="boolean"/>
        </all>
    </complexType>
</schema>

=== bugati23/Multithreading/src/test/resources/Trains.xml
<?xml version='1.0' encoding='UTF-8'?>
<trains xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/trains"
         xsi:schemaLocation="http://www.example.com/trains  Train.xsd">
    <train>
        <number>1</number>
        <direction>true</direction>
    </train>
    <train>
        <number>2</number>
        <direction>false</direction>
    </train>
    <train>
        <number>3</number>
        <direction>true</direction>
    </train>
    <train>
        <number>4</number>
        <direction>true</direction>
    </train>
    <train>
        <number>5</number>
        <direction>true</direction>
    </train>
    <train>
        <number>6</number>
        <direction>false</direction>
    </train>
    <train>
        <number>7</number>
        <direction>true</direction>
    </train>
    <train>
        <number>8</number>
        <direction>false</direction>
    </train>
    <train>
        <number>9</number>
        <direction>false</direction>
    </train>
    <train>
        <number>10</number>
        <direction>true</direction>
    </train>
</trains>
